#!/bin/bash

# XFreeRDP script utilizing Zentity for password prompt
# Author: Zjemm
# Email: mail [at] sjemm {dot} net
# Please use/share/comment/reference
# Date: 23-08-2017
# Version 0.3

OUTPUT=$(zenity --forms --title="Enter Password" \
    --text="Enter your password" \
    --separator="," \
    --add-password="Password" )

OUTPUT_RESULTS=$?
if ((OUTPUT_RESULTS != 0)); then
    echo "No input"
    exit 1
fi
Blank=""
Password=$(awk -F, '{print $1}' <<<$OUTPUT)

xfreerdp /t:"$1" /v:$1 /d:$3 /u:$2 /p:$Password /drive:sharedhost,/home/<your-username-here> /sound:sys:pulse /microphone:sys:alsa /scale:180 +clipboard +fonts +aero /cert-ignore +auto-reconnect +sec-nla /f
Password=""
